export const COLORS = {
  background: '#F2F2F7',
  card: '#FFFFFF',
  cardSecondary: '#F8F8FA',
  textPrimary: '#1C1C1E',
  textSecondary: '#8E8E93',
  textTertiary: '#AEAEB2',
  glucides: '#FF9500',
  proteines: '#007AFF',
  lipides: '#34C759',
  caloriesBlue: '#32ADE6',
  caloriesArc: '#A8D8EA',
  navBackground: '#1C1C1E',
  navActive: '#FFFFFF',
  navInactive: '#8E8E93',
  scanCorners: '#B8A94E',
  scanTag: 'rgba(107, 114, 95, 0.85)',
  scoreOrange: '#F5A623',
  scoreBlue: '#007AFF',
  scoreGreen: '#34C759',
  border: '#D1D1D6',
  borderLight: '#E5E5EA',
  danger: '#FF3B30',
};

export const TEXTES = {
  nav: {
    accueil: 'Accueil',
    statistiques: 'Statistiques',
    profil: 'Profil',
  },
  dashboard: {
    bonjour: 'Bonjour !',
    totalCalories: 'Total Calories',
    glucidesRestants: 'Glucides restants',
    proteinesRestantes: 'Protéines restantes',
    lipidesRestants: 'Lipides restants',
    suiviDuJour: 'Suivi du jour',
    calories: 'Calories',
    aucunRepas: "Aucun repas enregistré aujourd'hui",
  },
  scanner: {
    scanEnCours: 'Scan en cours',
    analyseEnCours: 'Analyse en cours...',
    identificationAliments: 'Identification des aliments...',
    calculCalories: 'Calcul des calories...',
    prendrePhoto: 'Prendre une photo',
    galerie: 'Galerie',
  },
  resultats: {
    total: 'Total',
    kcal: 'Kcal',
    glucides: 'Glucides',
    proteines: 'Protéines',
    lipides: 'Lipides',
    scoreSante: 'Score santé',
    modifierDetails: 'Modifier les détails',
    suivant: 'Suivant',
    enregistrer: 'Enregistrer',
  },
  historique: {
    titre: 'Historique',
    sept_jours: '7 jours',
    trente_jours: '30 jours',
    repasEnregistres: 'repas enregistrés',
  },
  onboarding: {
    objectifTitre: 'Quel est votre objectif ?',
    perdre: 'Perdre du poids',
    maintenir: 'Maintenir mon poids',
    prendre: 'Prendre de la masse',
    continuer: 'Continuer',
    commencer: 'Commencer',
    infosTitre: 'Parlez-nous de vous',
    activiteTitre: "Votre niveau d'activité ?",
    sedentaire: 'Sédentaire',
    leger: 'Légèrement actif',
    modere: 'Modérément actif',
    actif: 'Actif',
    tres_actif: 'Très actif',
  },
  profil: {
    titre: 'Profil',
    joursConsecutifs: 'Jours consécutifs',
    repasCannes: 'Repas scannés',
    moyenneCalJour: 'Moyenne cal/jour',
    mesObjectifs: 'Mes objectifs',
    objectifCalorique: 'Objectif calorique',
    poidsActuel: 'Poids actuel',
    poidsCible: 'Poids cible',
    parametres: 'Paramètres',
    modeSombre: 'Mode sombre',
    notifications: 'Notifications',
    unites: 'Unités',
    deconnexion: 'Déconnexion',
  },
  jours: ['L', 'M', 'M', 'J', 'V', 'S', 'D'],
  typesRepas: {
    petit_dejeuner: 'Petit-déjeuner',
    dejeuner: 'Déjeuner',
    diner: 'Dîner',
    snack: 'Collation',
  },
};
